include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
